# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rentflow_pb2 as rentflow__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rentflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LeaseServiceStub(object):
    """Сервис для управления арендой
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLease = channel.unary_unary(
                '/rentflow.LeaseService/CreateLease',
                request_serializer=rentflow__pb2.CreateLeaseRequest.SerializeToString,
                response_deserializer=rentflow__pb2.CreateLeaseResponse.FromString,
                _registered_method=True)
        self.GetLease = channel.unary_unary(
                '/rentflow.LeaseService/GetLease',
                request_serializer=rentflow__pb2.GetLeaseRequest.SerializeToString,
                response_deserializer=rentflow__pb2.GetLeaseResponse.FromString,
                _registered_method=True)
        self.UpdateLease = channel.unary_unary(
                '/rentflow.LeaseService/UpdateLease',
                request_serializer=rentflow__pb2.UpdateLeaseRequest.SerializeToString,
                response_deserializer=rentflow__pb2.UpdateLeaseResponse.FromString,
                _registered_method=True)
        self.ListLeases = channel.unary_unary(
                '/rentflow.LeaseService/ListLeases',
                request_serializer=rentflow__pb2.ListLeasesRequest.SerializeToString,
                response_deserializer=rentflow__pb2.ListLeasesResponse.FromString,
                _registered_method=True)


class LeaseServiceServicer(object):
    """Сервис для управления арендой
    """

    def CreateLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLeases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLease': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLease,
                    request_deserializer=rentflow__pb2.CreateLeaseRequest.FromString,
                    response_serializer=rentflow__pb2.CreateLeaseResponse.SerializeToString,
            ),
            'GetLease': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLease,
                    request_deserializer=rentflow__pb2.GetLeaseRequest.FromString,
                    response_serializer=rentflow__pb2.GetLeaseResponse.SerializeToString,
            ),
            'UpdateLease': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLease,
                    request_deserializer=rentflow__pb2.UpdateLeaseRequest.FromString,
                    response_serializer=rentflow__pb2.UpdateLeaseResponse.SerializeToString,
            ),
            'ListLeases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLeases,
                    request_deserializer=rentflow__pb2.ListLeasesRequest.FromString,
                    response_serializer=rentflow__pb2.ListLeasesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rentflow.LeaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rentflow.LeaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeaseService(object):
    """Сервис для управления арендой
    """

    @staticmethod
    def CreateLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentflow.LeaseService/CreateLease',
            rentflow__pb2.CreateLeaseRequest.SerializeToString,
            rentflow__pb2.CreateLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentflow.LeaseService/GetLease',
            rentflow__pb2.GetLeaseRequest.SerializeToString,
            rentflow__pb2.GetLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentflow.LeaseService/UpdateLease',
            rentflow__pb2.UpdateLeaseRequest.SerializeToString,
            rentflow__pb2.UpdateLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLeases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentflow.LeaseService/ListLeases',
            rentflow__pb2.ListLeasesRequest.SerializeToString,
            rentflow__pb2.ListLeasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
