# Generated by Django 5.2.7 on 2025-11-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='fastapi_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='FastAPI ID отслеживания'),
        ),
        migrations.AddField(
            model_name='lease',
            name='last_event_type',
            field=models.CharField(default='LEASE_CREATED', max_length=50, verbose_name='Последнее событие Kafka'),
        ),
        migrations.AddField(
            model_name='lease',
            name='status',
            field=models.CharField(default='INITIATED', max_length=50, verbose_name='Статус аренды (Kafka)'),
        ),
    ]
